name: Deploy Angular to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso de depuraci√≥n para ver la estructura de directorios
      - name: Print environment variables and directory structure
        run: |
          echo "HOME: $HOME"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -R /home/runner/work/
          ls -R $GITHUB_WORKSPACE

      # Cambiar la ruta a la carpeta correcta (moverse a "todo-app")
      - name: Change working directory to todo-app
        run: cd $GITHUB_WORKSPACE/Frontend/todo-app

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Usamos el directorio donde se encuentra todo-app
      - name: Install dependencies
        run: npm install
        working-directory: $GITHUB_WORKSPACE/Frontend/todo-app  # Ruta correcta

      - name: Build Angular app
        run: npm run build --configuration=production
        working-directory: $GITHUB_WORKSPACE/Frontend/todo-app  # Ruta correcta para build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:v1 .
        working-directory: $GITHUB_WORKSPACE/Frontend/todo-app  # Ruta correcta para Docker

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:v1

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "frontend-todoapp"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "${{ secrets.DOCKER_USERNAME }}/frontend-app:v1"
